### ISSUE TITLE
Commands do not work

### ISSUE THREAD

**Issue by weedcrab** [GanerCodes/videoEditBot#10]
I am trying to use the command string "destroy se, start 4, vol 0, se, start 4, hf 12, se, start 4, tc Holy Shit, se, start 4, mus Aphex Twin Avril 14, muss 20" and it returns an error saying that it is unable to download the video. Similar commands do not work.

**Comment by FlashlightET** [comment]
i dont even get an error, what has been going on with the bot? there are 4 servers and it still doesnt want to process anything?
