### ISSUE TITLE
the bot just straight up isnt working most of the time, but hat works fine

### ISSUE THREAD

**Issue by FlashlightET** [GanerCodes/videoEditBot#12]
from just now: not working
![image from just now](https://user-images.githubusercontent.com/29938499/103593940-36368a80-4ec5-11eb-9698-db88c4bf7e65.png)
from last night: not working
![image](https://user-images.githubusercontent.com/29938499/103594062-91687d00-4ec5-11eb-8cd5-cbdb20d485a6.png)
from earlier last night: working fine
![image](https://user-images.githubusercontent.com/29938499/103594085-a9d89780-4ec5-11eb-9c16-21f58a82e8b1.png)

this has been going on for the past month, for 70% of the times we use the bot. what is going on behind the scenes? clearly the destroy command somewhat works, because it still shows the cooldown when i try to destroy again, and also sometimes works for real during random times of day. it's very sporadic. not anything against the bot, just really curious as to why in the world it just sometimes doesnt want to work at all lately.

edit: just witnessed it before my very eyes
![image](https://user-images.githubusercontent.com/29938499/103834477-85112b00-5051-11eb-877e-36d6164bbd64.png)

**Comment by CaptainStabs** [comment]
Pretty sure the servers are just overloaded. My video eventually loaded, it just took 10 minutes.

**Comment by rafitamolin** [comment]
still happening
