### ISSUE TITLE
download.py bug

### ISSUE THREAD

**Issue by jaigitrep159** [GanerCodes/videoEditBot#18]
![bandicam 2021-05-10 16-42-54-993](https://user-images.githubusercontent.com/76834328/117631472-dd4a6c00-b1ae-11eb-8c6e-7499789e2755.jpg)
huh? but how do i fix this

**Comment by GanerCodes** [comment]
i have no clue if the cmd version of download works, try importing the library in a script

**Comment by jaigitrep159** [comment]
what import library

**Comment by GanerCodes** [comment]
download

**Comment by jaigitrep159** [comment]
download?

but how
