### ISSUE TITLE
"acid" command doesn't work.

### ISSUE THREAD

**Issue by Se7enSlasher** [GanerCodes/videoEditBot#22]
I tried this command first time and didn't work for now on. Can you fix this problem?

**Comment by GanerCodes** [comment]
it makes the filesize really big so it prob didn't get uploaded, try doing it on a rlly short video

**Comment by Se7enSlasher** [comment]
Due to Discord limitations to 8MB?

**Comment by GanerCodes** [comment]
yea

**Comment by OfficialIncubo** [comment]
Hmmmm. Please implement to upload the edited video to the cloud, then upload the edited mp4 link to Discord used by the commands.

That's a solution that I had.
