### ISSUE TITLE
can we get a proper documentation please?

### ISSUE THREAD

**Issue by neddien** [GanerCodes/videoEditBot#27]
can we get a proper documentation where it tells us what the fuck are these parameters and how to set the bot to run locally?

**Comment by GanerCodes** [comment]
what's the magic word?

**Comment by Nathidraws** [comment]
Please.

How would one set it up for Twitter?
@GanerCodes

**Comment by NeddX** [comment]
> what's the magic word?

My balla bitch

**Comment by duckduckstab1** [comment]
Docccumentatttttiiiiooooooooonnnnnnn:
pip install
python3 discordBot.py

**Comment by Nathidraws** [comment]
1 Year later
Nothing

**Comment by neddien** [comment]
retarded owner
