### ISSUE TITLE
Offline bot

### ISSUE THREAD

**Issue by MasterNama2008** [GanerCodes/videoEditBot#6]
Please fix this
![image](https://user-images.githubusercontent.com/71924055/100439668-d2e95980-30c9-11eb-99a0-03defd452ce6.png)

**Comment by guldenpvl2018-code** [comment]
@@@@@@@#######@######82 - 

[ ] 1. > [`_**_****___**_`]([url]([url]([url]([url](url)))))

**Comment by guldenpvl2018-code** [comment]
****
