### ISSUE TITLE
Videoedit bot broke autotunebot ENTIRELY

### ISSUE THREAD

**Issue by Jamieisbest** [GanerCodes/videoEditBot#64]
So I apparently got disappointed in VEB for not fixing Auto tune bot

Here's what happened

So I was thinking of making IDFB electronic sounds, so I putted "destroy autotune(link)". well guess what, when it exported the audio was the fricking same, I guess autotunebot is discontinued or something? Anyone tell me how to fix this, and if not then VEB will have to fix it himself.

That's all there is

**Comment by DevelopCMD** [comment]
Hello Jameisbest, if you want the same VideoEditBot experience with AutoTuneBot, join the OpenBots server: https://bit.ly/OpenBotsServer

**Comment by DevelopCMD** [comment]
Why did my comment get deleted?
But OpenVideoBot is better than VideoEditBot!

**Comment by DevelopCMD** [comment]
STOP DELETING MY COMMENTS! OPENVIDEOBOT HAS BEEN INVITED TO OVER 75 SERVERS AND ITS SUPPORT SERVER HAS 98 MEMBERS!

**Comment by DevelopCMD** [comment]
stop deleting my comments

**Comment by DevelopCMD** [comment]
I have no idea. also bro stop deleting my comments or else i'll delete my account

**Comment by sinogrime** [comment]
The reason why it's not working for you is probably because you are using the command wrong. It should be done as so:
`destroy autotune=<link>` and not like `destroy autotune("<link>")`. Even if you do manage to get the syntax right and the bot returns the same video untouched, there's a chance it failed downloading media from the link you gave it (from my own experiences).

**Comment by sinogrime** [comment]
Downloading the audio from SoundCloud will result in the error `[out#0/wav @ <memory address>] Error muxing a packet` and downloading from YouTube results in the error `ERROR: [youtube] <video ID>: Video unavailable`.

**Comment by sinogrime** [comment]
@Jamieisbest, the best way you will be able to solve this is by hosting VideoEditBot yourself on a Windows machine so it's able to use the autotune.exe to its best ability.

**Comment by sinogrime** [comment]
> Downloading the audio from SoundCloud will result in the error `[out#0/wav @ <memory address>] Error muxing a packet` and downloading from YouTube results in the error `ERROR: [youtube] <video ID>: Video unavailable`.

I was able to fix downloading in my pull here: https://github.com/GanerCodes/videoEditBot/pull/66
The packet muxing error is because of the autotune command's lack of support on Unix machines.

**Comment by GanerCodes** [comment]
closing this, for linux you need wine installed and autotune should theoretically work i think. if the wine stuff isn't working someone pls open another issue abt that
