### ISSUE TITLE
yt-dlp cripples music/autotune(?) ability of bot

### ISSUE THREAD

**Issue by sinogrime** [GanerCodes/videoEditBot#65]
I self host VEB on my own server and I noticed that commands that use the music/autotune options fail. I realised the problem is that args are put in lowercase, which affects youtube video IDs as so:
`youtu.be/rp4vQjrBKBw` becomes `youtu.be/rp4vqjrbkbw`, which results in: `ERROR: [youtube] rp4vqjrbkbw: Video unavailable`

Currently looking to find where in the code this happens so I can get rid of it

**Comment by sinogrime** [comment]
The temporary solution I've found is to disable `.lower()` on line ~344.
`cmd = spl[0].strip().lower()` appears to be the first command in the message (not destroy), so stopping the string from being converted from lowercase will stop YouTube video IDs from being affected - however people who are unfamiliar with the bot will have trouble using it if they use uppercases in their commands - this is because the bot handles commands in lowercase and that's hardcoded.
![Screenshot](https://github.com/GanerCodes/videoEditBot/assets/23375596/46c64c68-e88d-44cf-a334-09473fb442e2)

**Comment by GanerCodes** [comment]
can u try changing around 357 to:
```
if not ev1 or cmd == "":
            args = f"{spl[0].strip()} {args}" #
```
and see if that fixes it?

**Comment by sinogrime** [comment]
Because args comes after cmd, cmd would have to not be lowercased. I have fixed the issue I faced (and another) here: https://github.com/GanerCodes/videoEditBot/pull/66

I am not sure about the other issue regarding AutotuneBot but I am looking into it.
