### ISSUE TITLE
We need more commands like these

### ISSUE THREAD

**Issue by Jamieisbest** [GanerCodes/videoEditBot#68]
Hello VEB,

so I was thinking, if you want to update the bot, then you have to make some more commands. Like for example: Swirl, explode, implode etc.

Also, please improve the texts commands

**Comment by sinogrime** [comment]
What's wrong with the 'texts commands'?

**Comment by Jamieisbest** [comment]
Oh I forgot you fixed them

**Comment by Jamieisbest** [comment]
But add more commands, it'll be my PLEASURE

**Comment by Jamieisbest** [comment]
No do you make commands?

**Comment by sinogrime** [comment]
What?

**Comment by Jamieisbest** [comment]
Can you make commands?

**Comment by GanerCodes** [comment]
this is stupid
