### ISSUE TITLE
The commands are not working....

### ISSUE THREAD

**Issue by Spiral2839** [GanerCodes/videoEditBot#9]
now in discord, I was trying to command `destroy rc=20` but it didn't work...

**Comment by Spiral2839** [comment]
`destroy sfx=25` works, but some of the commands won't work
if you guys already fixed some of the commands, so thanks

**Comment by Spiral2839** [comment]
an error found while the bot is trying to download the file [if I used a command]

**Comment by Spiral2839** [comment]
Again, the command didn't worked right now...

**Comment by Spiral2839** [comment]
These commands are not working again still...

**Comment by Epictyphlosion** [comment]
The bot seems to be down again. I can't find any other place to contact the developer either.
